### ISSUE TITLE
noob needing some help

### ISSUE THREAD

**Issue by shoyrock** [HoppersPS4/Waste_Ur_Time#4]
![image](https://github.com/HoppersPS4/Waste_Ur_Time/assets/51036435/3218e4bf-2a4e-4d7f-8a62-d34cfb5a7bd9)
![image](https://github.com/HoppersPS4/Waste_Ur_Time/assets/51036435/1ab8ffd9-1200-416f-ab8e-8ccba7132750)
how do I go about using this tool?

**Comment by HoppersPS4** [comment]
PS4_Passcode_Bruteforcer_x86.exe MyPackage.pkg MyFolder
Make sure to use the 1.06 or the latest beta.

**Comment by shoyrock** [comment]
I'm using Update-1.07.1b

**Comment by HoppersPS4** [comment]
https://github.com/HoppersPS4/Waste_Ur_Time/releases/download/Update-1.06/PS4_Passcode_Bruteforcer_x86.exe

Use this version please and report back =)

**Comment by shoyrock** [comment]
Nice it's working, how do I go about using the supported CIDs.txt

**Comment by shoyrock** [comment]
nice it works time to waste some time. Hopefully I can find the ps4.txt

**Comment by HoppersPS4** [comment]
Pretty sure those Passcodes are copyrighted, im not looking to get sued lol.
But otherwise, nice to see u get it working.

**Comment by HoppersPS4** [comment]
but if you message me on discord, i could potentially help you out.
Discord: hoppers

**Comment by shoyrock** [comment]
Just added, was the GPU bug ever fixed
