### ISSUE TITLE
Invalid PS4 package file header

### ISSUE THREAD

**Issue by comradesean** [HoppersPS4/Waste_Ur_Time#5]
Running this on a PS4 pkg downloaded directly off their CDN. It's a US pkg.

![image](https://github.com/HoppersPS4/Waste_Ur_Time/assets/203258/f5ad168d-d62d-476c-be13-64fadeb63d99)

**Comment by HoppersPS4** [comment]
Make sure to use 1.06 or the beta right after, latest is having issues which I’m gonna address this month.

**Comment by comradesean** [comment]
Understood. Thank you.

**Comment by HoppersPS4** [comment]
Will mark this as done, thanks for wasting your time.
